export const sideProjects = [
  {
    title: "Do You Play Badminton",
    projLink: "https://www.doyouplaybadminton.com/",
    desc: "a shareable player card for when someone asks if you play, plus courts and discount alerts in Bengaluru.",
    descLink: "/projects/doyouplaybadminton/",
    userCount: "13 users",
    activelyWorking: false,
  },
  {
    title: "Bhondu Life",
    projLink: "https://www.bhondugame.com/",
    desc: "a desi turn-based life simulator where every day throws a new, hilariously relatable situation at you.",
    descLink: "/projects/bhondu-game/",
    userCount: "170 users",
    activelyWorking: true,
  },
  {
    title: "MyYearOnX",
    projLink: "https://www.myyearonx.com/",
    desc: "spotify wrapped but for X (Twitter) - your year on X, beautifully visualized.",
    descLink: "/projects/myyearonx/",
    userCount: null,
    activelyWorking: true,
  },
  {
    title: "Farside",
    projLink: "https://farside.shivamtaneja.com/",
    desc: "look away and get the iPhone Duo-style fade. webcam-based, fully on-device.",
    descLink: "/projects/farside/",
    userCount: null,
    activelyWorking: true,
  },
  {
    title: "Exactly What I Have Been Looking For",
    projLink: "https://www.exactlywhatihavebeenlookingfor.com/",
    desc: "a growing, crowdsourced database of useful-but-forgettable tools and links, with a touch of desi humor.",
    descLink: "/projects/exactlywhatihavebeenlookingfor/",
    userCount: null,
    activelyWorking: false,
  },
  {
    title: "The Guy She Told You About",
    projLink: "https://www.theguyshetoldyouabout.com/",
    desc: "my another profile/portfolio i got just cause for funziess xD so it has details about me and its like a fun random domain i bought.",
    descLink: "/projects/theguyshetoldyouabout/",
    userCount: null,
    activelyWorking: false,
  },
  {
    title: "GraphMySelf",
    projLink: "https://www.graphmyself.com/",
    desc: "a personal AI memory layer that knows who you are, so every AI tool you use stops starting from zero.",
    descLink: "/projects/graphmyself/",
    userCount: "5 users",
    activelyWorking: false,
  },
  {
    title: "MySkillRoad",
    projLink: "https://www.myskillroad.com/",
    desc: "a personalized learning roadmap that tracks your growth across platforms and tells you exactly what to learn next.",
    descLink: "/projects/myskill-road/",
    userCount: null,
    activelyWorking: false,
  },
  {
    title: "EZNotify",
    projLink: "https://www.eznotify.dev/",
    desc: "a developer friendly SDK for sending multi-channel notifications like email, SMS, WhatsApp, push and more built for reliability at scale.",
    descLink: "/projects/eznotify/",
    userCount: null,
    activelyWorking: false,
  },
  {
    title: "DecodeMyCode",
    projLink: "https://www.decodemycode.com/",
    desc: "an AI powered SaaS that turns any code into clear explanations, flowcharts and summaries.",
    descLink: "/projects/decode-mycode/",
    userCount: "5 users",
    activelyWorking: false,
  },
  {
    title: "CollabWrite",
    projLink: "https://collabwrite.appwrite.network/",
    desc: "an open source, real-time collaborative knowledge-sharing platform.",
    descLink: "/projects/collab-write/",
    userCount: "10 users",
    activelyWorking: false,
  },
  {
    title: "NagarIQ",
    projLink: "https://nagar-iq.shivamtaneja.com/",
    desc: "an AI-powered system that understands the world around it.",
    descLink: "/projects/nagar-iq/",
    userCount: "12 users",
    activelyWorking: false,
  },
  {
    title: "Tilt Bot",
    projLink: "https://tilt-bot.shivamtaneja.com/",
    desc: "an AI-powered gaming roast generator for witty, non-toxic comebacks.",
    descLink: "/projects/tilt-bot/",
    userCount: "05 users",
    activelyWorking: false,
  },
  {
    title: "Chat Mingle",
    projLink: "https://chat-mingle.shivamtaneja.com/",
    desc: "a fun, experimental chat app.",
    descLink: "/projects/chat-mingle/",
    userCount: "19 users",
    activelyWorking: false,
  },
  {
    title: "Circle Catcher",
    projLink: "https://circle-game.shivamtaneja.com/",
    desc: "a game where you grow by eating smaller circles while avoiding larger ones.",
    descLink: "/projects/circle-catcher/",
    userCount: "09 users",
    activelyWorking: false,
  },
  {
    title: "Career Guide Hub (Freelance)",
    projLink: "https://www.saina.co.in/",
    desc: "a web app with assessments to provide personalized career recommendations, empowering student decisions.",
    descLink: "/projects/career-guidance/",
    userCount: null,
    activelyWorking: false,
  },
];
