import type { IconType } from "react-icons";
import {
  FaFacebook,
  FaGithub,
  FaGlobe,
  FaInstagram,
  FaLinkedin,
  FaTwitter,
  FaYoutube,
} from "react-icons/fa";
import {
  SiAboutdotme,
  SiBiolink,
  SiBluesky,
  SiBuymeacoffee,
  SiCalendly,
  SiCodeberg,
  SiCredly,
  SiDailydotdev,
  SiDevdotto,
  SiDevpost,
  SiDiscord,
  SiDocker,
  SiGitlab,
  SiHuggingface,
  SiKaggle,
  SiLeetcode,
  SiMedium,
  SiNpm,
  SiProducthunt,
  SiRoadmapdotsh,
  SiThreads,
} from "react-icons/si";

export type Social = {
  id: string;
  heading: string;
  link: string;
  icon: IconType;
  showInNav: boolean;
  description?: string;
  /** Canonical profile URL for schema sameAs when `link` is an intent/action URL. */
  profileUrl?: string;
  /** Include in schema.org sameAs. Defaults to true. */
  sameAs?: boolean;
};

export const socials: Social[] = [
  {
    id: "linkedin",
    heading: "LinkedIn",
    link: "https://www.linkedin.com/in/shivam-taneja/",
    icon: FaLinkedin,
    showInNav: true,
    description: "Career updates and professional network.",
  },
  {
    id: "github",
    heading: "GitHub",
    link: "https://github.com/shivam-taneja",
    icon: FaGithub,
    showInNav: true,
    description: "Code, repos, and open source.",
  },
  {
    id: "twitter",
    heading: "Twitter / X",
    link: "https://twitter.com/intent/follow?screen_name=codesbyshivam",
    icon: FaTwitter,
    showInNav: true,
    description: "Short takes and build-in-public.",
    profileUrl: "https://twitter.com/codesbyshivam",
  },
  {
    id: "youtube",
    heading: "YouTube",
    link: "https://www.youtube.com/@codesbyshivam?sub_confirmation=1",
    icon: FaYoutube,
    showInNav: true,
    description: "Dev videos and what I'm building.",
    profileUrl: "https://www.youtube.com/@codesbyshivam",
  },
  {
    id: "instagram",
    heading: "Instagram",
    link: "https://www.instagram.com/codesbyshivam/",
    icon: FaInstagram,
    showInNav: true,
    description: "Behind the scenes @codesbyshivam.",
  },
  {
    id: "threads",
    heading: "Threads",
    link: "https://www.threads.net/@codesbyshivam",
    icon: SiThreads,
    showInNav: false,
    description: "Short posts @codesbyshivam.",
  },
  {
    id: "bluesky",
    heading: "Bluesky",
    link: "https://bsky.app/profile/codesbyshivam.com",
    icon: SiBluesky,
    showInNav: false,
    description: "Posts on Bluesky.",
  },
  {
    id: "facebook",
    heading: "Facebook",
    link: "https://www.facebook.com/codesbyshivam/",
    icon: FaFacebook,
    showInNav: false,
    description: "Updates on Facebook.",
  },
  {
    id: "discord",
    heading: "Discord",
    link: "https://discord.com/users/378431901880549376",
    icon: SiDiscord,
    showInNav: false,
    description: "Username: .drunkenengineer",
  },
  {
    id: "producthunt",
    heading: "Product Hunt",
    link: "https://www.producthunt.com/@shivamtaneja",
    icon: SiProducthunt,
    showInNav: false,
    description: "Launches and maker profile.",
  },
  {
    id: "npm",
    heading: "npm",
    link: "https://www.npmjs.com/~shivamtaneja",
    icon: SiNpm,
    showInNav: false,
    description: "Published packages.",
  },
  {
    id: "leetcode",
    heading: "LeetCode",
    link: "https://leetcode.com/shivam-taneja/",
    icon: SiLeetcode,
    showInNav: false,
    description: "Problem solving practice.",
  },
  {
    id: "kaggle",
    heading: "Kaggle",
    link: "https://www.kaggle.com/shiivamtaneja",
    icon: SiKaggle,
    showInNav: false,
    description: "Data science and competitions.",
  },
  {
    id: "huggingface",
    heading: "Hugging Face",
    link: "https://huggingface.co/shivamtaneja",
    icon: SiHuggingface,
    showInNav: false,
    description: "Models and ML experiments.",
  },
  {
    id: "docker",
    heading: "Docker Hub",
    link: "https://hub.docker.com/u/codesbyshiv",
    icon: SiDocker,
    showInNav: false,
    description: "Container images.",
  },
  {
    id: "gist",
    heading: "GitHub Gist",
    link: "https://gist.github.com/shivam-taneja",
    icon: FaGithub,
    showInNav: false,
    description: "Snippets and notes.",
  },
  {
    id: "gitlab",
    heading: "GitLab",
    link: "https://gitlab.com/shivamtaneja",
    icon: SiGitlab,
    showInNav: false,
    description: "Repos and CI on GitLab.",
  },
  {
    id: "codeberg",
    heading: "Codeberg",
    link: "https://codeberg.org/shivamtaneja",
    icon: SiCodeberg,
    showInNav: false,
    description: "FOSS-friendly git hosting.",
  },
  {
    id: "devto",
    heading: "DEV",
    link: "https://dev.to/shivamtaneja",
    icon: SiDevdotto,
    showInNav: false,
    description: "Articles on DEV Community.",
  },
  {
    id: "medium",
    heading: "Medium",
    link: "https://medium.com/@codesbyshivam",
    icon: SiMedium,
    showInNav: false,
    description: "Long-form writing.",
  },
  {
    id: "gdev",
    heading: "Google Developers",
    link: "https://g.dev/codesbyshivam",
    icon: FaGlobe,
    showInNav: false,
    description: "Google Developer profile.",
  },
  {
    id: "roadmap",
    heading: "roadmap.sh",
    link: "https://roadmap.sh/u/shivamtaneja",
    icon: SiRoadmapdotsh,
    showInNav: false,
    description: "Learning roadmaps progress.",
  },
  {
    id: "dailydev",
    heading: "daily.dev",
    link: "https://app.daily.dev/shivamtaneja",
    icon: SiDailydotdev,
    showInNav: false,
    description: "Developer news profile.",
  },
  {
    id: "credly",
    heading: "Credly",
    link: "https://www.credly.com/users/shivamtaneja/badges/credly",
    icon: SiCredly,
    showInNav: false,
    description: "Verified badges and certs.",
  },
  {
    id: "devfolio",
    heading: "Devfolio",
    link: "https://devfolio.co/@codesbyshivam",
    icon: FaGlobe,
    showInNav: false,
    description: "Hackathon profile.",
  },
  {
    id: "devpost",
    heading: "Devpost",
    link: "https://devpost.com/shivamtaneja",
    icon: SiDevpost,
    showInNav: false,
    description: "Hackathon projects.",
  },
  {
    id: "unfair",
    heading: "Unfair",
    link: "https://unfair.so/@codesbyshivam",
    icon: FaGlobe,
    showInNav: false,
    description: "Creator profile on Unfair.",
  },
  {
    id: "aboutme",
    heading: "about.me",
    link: "https://about.me/codesbyshivam",
    icon: SiAboutdotme,
    showInNav: false,
    description: "Short profile bio.",
  },
  {
    id: "bbbio",
    heading: "bb.bio",
    link: "https://bb.bio/shivamtaneja",
    icon: SiBiolink,
    showInNav: false,
    description: "Link-in-bio page.",
    sameAs: false,
  },
  {
    id: "calendly",
    heading: "Calendly",
    link: "https://calendly.com/shivamtaneja/",
    icon: SiCalendly,
    showInNav: false,
    description: "Book a call.",
    sameAs: false,
  },
  {
    id: "buymeacoffee",
    heading: "Buy Me a Coffee",
    link: "https://buymeacoffee.com/codesbyshivam",
    icon: SiBuymeacoffee,
    showInNav: false,
    description: "Support the work.",
    sameAs: false,
  },
];

export const navSocials = socials.filter((s) => s.showInNav);

/** Identity URLs for schema.org sameAs (never intent/action or utility links). */
export const socialProfileUrls = socials
  .filter((s) => s.sameAs !== false)
  .map((s) => s.profileUrl ?? s.link);
